 name: Show GitHub context
 on: push
 jobs:
   my-job:
     runs-on: ubuntu-latest
   steps:
     - name: step
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
